version: '3'

services:
  netlify:
    container_name: netlify
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    environment:
      NETLIFY_AUTH_TOKEN: ${NETLIFY_AUTH_TOKEN}
      NETLIFY_SITE_NAME: ${NETLIFY_SITE_NAME}
      NETLIFY_PUBLISH_FOLDER: ${NETLIFY_PUBLISH_FOLDER}